### ISSUE TITLE
Does Nether Bedrock Cracker work on Ubuntu?

### ISSUE THREAD

**Issue by Jeffery879** [19MisterX98/Nether_Bedrock_Cracker#17]
Does Nether Bedrock Cracker work on Ubuntu? I tried to run it on another Linux distribution but when I double clicked it nothing happened. Also in the properties it said it was an executable file. 

Thanks in advance,

Jeffrey.

**Comment by 19MisterX98** [comment]
Files aren't executable by default as a security measure. You can make it executable in the permissions tab of the file properties. You can also use chmod in the terminal
