### ISSUE TITLE
How to insert data into main.rs

### ISSUE THREAD

**Issue by FlailoftheLord** [19MisterX98/Nether_Bedrock_Cracker#6]
I don't understand what's happening when i open the main.rs, it's asking for a filename, but doesn't specify the path... where do i insert the coordinates?

**Comment by 19MisterX98** [comment]
Readme is outdated, either you go sone commits back and edit the file
or 
you can write coords into a new file via the format
x y z
x y z
x y z

Then parse the file path as a command argument 
cargo run -- path/to/coords.txt

In case of the file being in the directory
cargo run -- coords.txt

**Comment by FlailoftheLord** [comment]
![Screenshot_20230406_132133](https://user-images.githubusercontent.com/41513161/230451244-df7c4c46-7a1b-412a-8c61-e2497922e343.png)
Panics on an unwrap error.

**Comment by FlailoftheLord** [comment]
Found this.
https://users.rust-lang.org/t/thread-main-panicked-at-called-result-unwrap-on-an-err-value-error-expected-value/68820

**Comment by 19MisterX98** [comment]
I made some changes for better errors. try again
