### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Darkable** [19MisterX98/Nether_Bedrock_Cracker#8]
bedrock_cracker-windows.exe : The term 'bedrock_cracker-windows.exe' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ bedrock_cracker-windows.exe -- coords.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (bedrock_cracker-windows.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
 I got this issue in powershell when I have the binary and coords.txt in the same folder

**Comment by ziloka** [comment]
the readme assumes you are first in the directory that has both files. 
make sure you rename the file you downloaded to have the exe file extension

Run this intead
```pwsh
.\bedrock_cracker-windows.exe coords.txt
```

**Comment by Darkable** [comment]
thread 'main' panicked at 'assertion failed: self.upper_bound > self.lower_bound', src\lib.rs:72:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

After I ran that I got this message, pretty sure it's just broken and I can't do anything, but I was just wandering if there is an unlikely fix.
